projects:
  app:
    schemaPath: apollo-server/schema.graphql
    includes:
      - '**/*.gql'
    extensions:
      endpoints:
        default: 'https://api.github.com/graphql?user_name='YocelinGR'&access_token='931cdabb794dfdd2bdd4980bb97a570fa6bc12ce''
